### ISSUE TITLE
trouble installing prepr - gmp not found

### ISSUE THREAD

**Issue by tungxphung** [prioritizr/aoh#52]
Hello,
I apologize in advance for that this issue isn't directly related to aoh.
I am having trouble installing prepr on a Mac M1. I was able to install all necessary dependencies but I get the error "configure: GNU MP not found". When I run "brew install gmp" again in the terminal, the system informs me that it is already installed.
I would appreciate any suggestions.

**Comment by jeffreyhanson** [comment]
Hi @tungxphung!

Thanks for reaching out! I'm sorry, I don't have a M1 Mac and I don't know of any known fixes to this issue. I was going to suggest posting on the prepr github repo, but I see you've already done that. 

Here's one idea - probably a long shot but might be worth trying? According to this Stackoverflow post (https://stackoverflow.com/questions/76263637/how-do-i-install-gmp-into-xcode-with-brew), Homebrew installs stuff in a non-standard location for M1 Mac's.  So perhaps one solution is to help the package configure script (the code that displays the error `configure: GNU MP not found`) and R (when subsequently installing prepr) find where gmp is installed? 

Could you try editing your system's `PATH` variable to include the `/opt/homebrew/include` and `/opt/homebrew/lib` directories? This might be possible by adding the following text to `${HOME}/.bash_profile` (see here for more info: https://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable/):

```
export PATH="${PATH}:/opt/homebrew/include:/opt/homebrew/lib"
```

How does that sound? After adding the text, you might need to restart R or your computer for the changes to take effect.

**Comment by jeffreyhanson** [comment]
@tungxphung, I just wanted to follow up and see if you were able to get this working? Did changing the `$PATH` help?

**Comment by tungxphung** [comment]
Hello,
Unfortunately I still have not been able to solve this. Together with suggestions from this thread ( https://stackoverflow.com/questions/70497361/homebrew-mac-m1-cant-find-installs)  I added a bunch of paths (and also tweaked them around a little) but that did not help:

```
export PATH="${PATH}:/opt/homebrew/include:/opt/homebrew/lib"
export PATH="${PATH}:/opt/homebrew/bin:/opt/homebrew/opt"
export CPATH=/opt/homebrew/include
export CPATH=/opt/homebrew/opt
export LIBRARY_PATH=/opt/homebrew/lib
```
I also noticed that when I searched for gmp in the homebrew folder nothing turns up in bin, include, or lib. There's a gmp folder in opt/homebrew/opt
I'll try a different device but I hope there'll be some help soon

**Comment by tungxphung** [comment]
Here is the list of files and folders in opt/gmp/6.3.0 :

```
AUTHORS
ChangeLog
COPYING
COPYING.LESSERv3
include
gmp.h
gmpxx.h
INSTALL_RECEIPT.json
lib
libgmp.10.dylib
libgmp.a
libgmp.dylib
libgmpxx.4.dylib
libgmpxx.a
libgmpxx.dylib
pkgconfig
gmp.pc
gmpxx.pc
NEWS
README
share
info
gmp.info
gmp.info-1
gmp.info-2
```

**Comment by jeffreyhanson** [comment]
Thanks! Could you please give it a try with this:

```
export PATH="${PATH}:/opt/homebrew/opt/gmp/6.3.0/include"
export PATH="${PATH}:/opt/homebrew/opt/gmp/6.3.0/lib"
```

Or if that doesn't work, then maybe this?

```
export PATH="${PATH}:/opt/homebrew/opt/gmp/6.3.0"
```

**Comment by tungxphung** [comment]
thank you again for your patience. Editing the PATH in various ways still has not worked out for me. The results for the above commands are:

```
pkg-config gmp --cflags
-I/opt/local/include

pkg-config gmp --libs
-L/opt/local/lib -lgmp
```

**Comment by jeffreyhanson** [comment]
Hmm, could you please try this?

```
export PATH="${PATH}:/opt/local/include:/opt/local/lib"
```

**Comment by tungxphung** [comment]
FIY, I believe the package is failing to build according to its GitHub tags ( https://github.com/dickoa/prepr?tab=readme-ov-file )
I do  not have the knowledge to understand what's going on when I click on those tags, but it might be useful to alert future users

**Comment by jeffreyhanson** [comment]
Thanks for pointing this out! Yeah, the automated checks for prepr are indeed failing. In particular, these checks are related to (1) calculating package test coverage statistics and rebuilding the package website (see https://gitlab.com/dickoa/prepr/-/jobs/3299598150), and (2) checking the package on a Windows platform (https://ci.appveyor.com/project/dickoa/prepr/builds/45332027). Personally, I'm not too worried about these failing checks because they are both failing because of issues encountered with installing dependencies---which is not surprising since these checks are done using the GitLab and AppyVeyor platforms which AFAIK aren't very well maintained for checking R packages (personally, I prefer GitHub Actions for checking R packages). Also, the package hasn't been updated in 2 years which, at least, means that these failing checks aren't due to new, recently introduced bugs.

Were you able to find a work around by using another computer? It might be possible to submit a patch for prepr that fixes this issue, but I might need some help over zoom/teams/etc so that someone with a M1 Mac can try different things to see if it works. I'll post on the prepr repo and see if the maintainer would be open to a PR.

**Comment by tungxphung** [comment]
Unfortunately not yet - I will report back if a fix comes through!
I am also happy to assist over zoom in the future if necessary, as IUCN data in general is important to my thesis

**Comment by jeffreyhanson** [comment]
Just to give an update, I've created a fork of prepr which seems to work on M1 Macs (https://github.com/prioritizr/prepr). Could you try installing that and seeing if it works with the aoh package? I've also updated the aoh docs to point users to the fork for installing prepr.

**Comment by jeffreyhanson** [comment]
Since I've updated the package to now refer to the prioritizr prepr fork which can install on M1 Macs, I'll close this issue. Please feel free to reopen it though if you're still having trouble getting it to work.
